on:
  fork:
  push:
    branches: [main]
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened]
  pull_request_review_comment:
    types: [created]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: YurisCodingClub/dev-cv/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "<h1>It's great having you contribute to this project</h1> Welcome to the club :nerd_face:"
          pr-message: "<h1>It's great having you contribute to this project</h1> Welcome to the club :nerd_face:"
